improved the script ``doodle''
- removed colordisp
- uses a function ``dood'' to disp&run a command line

diff --git a/doodle b/doodle
--- a/doodle
+++ b/doodle
@@ -1,147 +1,142 @@
 #!/bin/bash
 
 promptcolor="\033[31m"
+bannercolor="\033[32m"
 cmdcolor="\033[36m"
+commentcolor="\033[1;35m"
+sepcolor="\033[37m"
+errcolor="\033[1;31m"
 nocolor="\033[0m"
-disp=./colordisp
 
-$disp "######################################################################"
+dood() {
+    line=$*
+    firstword=`echo $line | awk -F " " '{print $1}'`
 
-$disp "/bin/rm -rf remote/"
-       /bin/rm -rf remote/
-$disp "/bin/rm -rf local/.git local/foo.txt"
-       /bin/rm -rf local/.git local/foo.txt
+    flag=0
+    for w in /bin/rm git pwd pushd popd echo touch cd cp diff mkdir cat; do
+	if [ "$firstword" == "$w" ]; then
+	    flag=1
+	fi
+    done
 
-$disp "mkdir remote"
-       mkdir remote
-$disp "git init --bare remote/doodle.git"
-       git init --bare remote/doodle.git
+    if [ "$flag" -eq 1 ]; then
+	echo -e $sepcolor"----------------------------------------------------------------------"$nocolor
+	cmdall="$*"
+	cmd=${cmdall%%#*}
+	comment=${cmdall##*#}
+	if [ "$cmdall" == "$cmd" ]; then
+	    echo -e $promptcolor"$ "$nocolor$cmdcolor"$cmd"$nocolor
+	else
+	    echo -e $promptcolor"$ "$nocolor$cmdcolor"$cmd"$commentcolor"#$comment"$nocolor
+	fi
 
-$disp "cd local"
-       cd local
+	cmd0=${cmd%%>*}
+	cmd1=${cmd##*>}
+	if [ "$cmd" == "$cmd0" ]; then
+	    $cmd
+	else
+	    $cmd0 >> $cmd1
+	fi
+    else
+	if [ "${line:0:2}" == "##" ] || [ "${line:0:2}" == "==" ]; then
+            echo -e $bannercolor"$*"$nocolor
+	else
+            echo -e "Error: "$errcolor$line$nocolor
+	    exit 100
+	fi
+    fi
+}
 
-disp=../colordisp
+dood "######################################################################"
 
-$disp "======================================================================"
+dood "/bin/rm -rf remote/"
+dood "/bin/rm -rf local/.git local/foo.txt"
 
-$disp "git init                                                            # init"
-       git init
-$disp "touch foo.txt                                                       # create foo.txt"
-       touch foo.txt
-$disp "git add foo.txt"
-       git add foo.txt .gitignore
-$disp "git commit -m 'first-commit'                                        # first commit"
-       git commit -m 'first-commit'
-$disp "git remote add origin ../remote/doodle.git"
-       git remote add origin ../remote/doodle.git
-$disp "git push -u origin master                                           # push"
-       git push -u origin master
+dood "mkdir remote"
+dood "git init --bare remote/doodle.git"
 
-$disp "echo \"a\" >> foo.txt                                                 # modify foo.txt"
-       echo "a" >> foo.txt
-$disp "git add foo.txt"
-       git add foo.txt
-$disp "git commit -m \"a\"                                                   # commit a"
-       git commit -m "a"
-$disp "git push                                                            # push"
-       git push
+dood "pushd local"
 
-$disp "echo \"b\" >> foo.txt                                                 # modify foo.txt"
-       echo "b" >> foo.txt
-$disp "git add foo.txt"
-       git add foo.txt
-$disp "git commit -m \"b\"                                                   # commit b"
-       git commit -m "b"
-$disp "git push                                                            # push"
-       git push
+dood "======================================================================"
 
-echo doodle.git.`git log --pretty=oneline | head -n 1 | cut -c1-7`-`head -c10 /dev/urandom | sha1sum | head -c 3` > /tmp/gitdoodle.bakname
-$disp "cp -r ../remote/doodle.git ../remote/`cat /tmp/gitdoodle.bakname`"
-       cp -r ../remote/doodle.git ../remote/`cat /tmp/gitdoodle.bakname`
+dood "pwd"
 
-$disp "echo \"This line is supposed to be a bad line in a bad commit-and-push to be undone.\" >> foo.txt         # modify foo.txt"
-       echo "This line is supposed to be a bad line in a bad commit-and-push to be undone." >> foo.txt
-$disp "git add foo.txt"
-       git add foo.txt
+dood "git init                                                            # init"
+dood "touch foo.txt                                                       # create foo.txt"
+dood "git add foo.txt"
+dood "git commit -m first-commit                                          # first commit"
+dood "git remote add origin ../remote/doodle.git"
+dood "git push -u origin master                                           # push"
 
-$disp "git commit -m \"bad\"                                                 # commit bad"
-       git commit -m "bad"
-$disp "git push                                                            # push"
-       git push
-$disp "git log --pretty=oneline"
-       git log --pretty=oneline
+dood "echo a >> foo.txt                                                   # modify foo.txt"
+dood "cat foo.txt"
+dood "git add foo.txt"
+dood "git commit -m a                                                     # commit a"
+dood "git push                                                            # push"
 
-$disp "git push -f origin HEAD^:master                                     # undo push"
-       git push -f origin HEAD^:master
-$disp "git st"
-       git st
-$disp "git log --pretty=oneline"
-       git log --pretty=oneline
-
-$disp "git reset --hard HEAD^                                              # get back to previous commit (will lose working tree)"
-       git reset --hard HEAD^
-$disp "git st"
-       git st
-$disp "git log --pretty=oneline"
-       git log --pretty=oneline
-
-$disp "diff -r ../remote/`cat /tmp/gitdoodle.bakname` ../remote/doodle.git       # difference before and after push&unpush"
-       diff -r ../remote/`cat /tmp/gitdoodle.bakname` ../remote/doodle.git
+dood "echo b >> foo.txt                                                   # modify foo.txt"
+dood "cat foo.txt"
+dood "git add foo.txt"
+dood "git commit -m b                                                     # commit b"
+dood "git push                                                            # push"
 
 echo doodle.git.`git log --pretty=oneline | head -n 1 | cut -c1-7`-`head -c10 /dev/urandom | sha1sum | head -c 3` > /tmp/gitdoodle.bakname
-$disp "cp -r ../remote/doodle.git ../remote/`cat /tmp/gitdoodle.bakname`"
-       cp -r ../remote/doodle.git ../remote/`cat /tmp/gitdoodle.bakname`
+dood "cp -r ../remote/doodle.git ../remote/`cat /tmp/gitdoodle.bakname`"
 
-$disp "echo \"This line is supposed to be a bad line in a bad commit-and-push to be undone.\" >> foo.txt         # modify foo.txt"
-       echo "This line is supposed to be a bad line in a bad commit-and-push to be undone." >> foo.txt
-$disp "git add foo.txt"
-       git add foo.txt
+dood "echo This line is supposed to be a bad line in a bad commit-and-push to be undone. >> foo.txt         # modify foo.txt"
+dood "cat foo.txt"
+dood "git add foo.txt"
 
-$disp "git commit -m \"bad\"                                                 # commit bad"
-       git commit -m "bad"
-$disp "git push                                                            # push"
-       git push
-$disp "git log --pretty=oneline"
-       git log --pretty=oneline
+dood "git commit -m bad                                                   # commit bad"
+dood "git push                                                            # push"
+dood "git log --pretty=oneline"
 
-$disp "git rebase -i HEAD~2                                                # delete the 2nd line in the editor"
-       git rebase -i HEAD~2
-$disp "git push origin +master                                             # undo push"
-       git push origin +master
-$disp "git st"
-       git st
-$disp "git log --pretty=oneline"
-       git log --pretty=oneline
+dood "git push -f origin HEAD^:master                                     # undo push"
+dood "git st"
+dood "git log --pretty=oneline"
 
-$disp "diff -r ../remote/`cat /tmp/gitdoodle.bakname` ../remote/doodle.git       # difference before and after push&unpush"
-       diff -r ../remote/`cat /tmp/gitdoodle.bakname` ../remote/doodle.git
+dood "git branch"
 
-$disp "echo \"a\" >> foo.txt                                                 # modify foo.txt"
-       echo "c" >> foo.txt
-$disp "git add foo.txt"
-       git add foo.txt
-$disp "git commit -m \"c\"                                                   # commit c"
-       git commit -m "c"
-$disp "git push                                                            # push"
-       git push
+dood "git reset --hard HEAD^                                              # get back to previous commit (will lose working tree)"
+dood "git st"
+dood "git log --pretty=oneline"
 
-$disp "echo \"d\" >> foo.txt                                                 # modify foo.txt"
-       echo "d" >> foo.txt
-$disp "git add foo.txt"
-       git add foo.txt
-$disp "git commit -m \"d\"                                                   # commit d"
-       git commit -m "d"
-$disp "git push                                                            # push"
-       git push
+dood "diff -r ../remote/`cat /tmp/gitdoodle.bakname` ../remote/doodle.git       # difference before and after push&unpush"
 
-$disp "git log --pretty=oneline"
-       git log --pretty=oneline
+echo doodle.git.`git log --pretty=oneline | head -n 1 | cut -c1-7`-`head -c10 /dev/urandom | sha1sum | head -c 3` > /tmp/gitdoodle.bakname
+dood "cp -r ../remote/doodle.git ../remote/`cat /tmp/gitdoodle.bakname`"
 
-$disp "======================================================================"
+dood "echo This line is supposed to be a bad line in a bad commit-and-push to be undone. >> foo.txt         # modify foo.txt"
+dood "cat foo.txt"
+dood "git add foo.txt"
 
-$disp "cd .."
-       cd ..
+dood "git commit -m bad                                                   # commit bad"
+dood "git push                                                            # push"
+dood "git log --pretty=oneline"
 
-disp=./colordisp
+dood "git rebase -i HEAD~2                                                # delete the 2nd line in the editor"
+dood "git push origin +master                                             # undo push"
+dood "git st"
+dood "git log --pretty=oneline"
 
-$disp "######################################################################"
+dood "diff -r ../remote/`cat /tmp/gitdoodle.bakname` ../remote/doodle.git       # difference before and after push&unpush"
+
+dood "echo c >> foo.txt                                                   # modify foo.txt"
+dood "cat foo.txt"
+dood "git add foo.txt"
+dood "git commit -m c                                                     # commit c"
+dood "git push                                                            # push"
+
+dood "echo d >> foo.txt                                                   # modify foo.txt"
+dood "cat foo.txt"
+dood "git add foo.txt"
+dood "git commit -m d                                                     # commit d"
+dood "git push                                                            # push"
+
+dood "git log --pretty=oneline"
+
+dood "======================================================================"
+
+dood "popd"
+
+dood "######################################################################"
